# Generated by Django 2.1.14 on 2019-12-01 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petshow', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='media/default.jpg', upload_to='profile_pics'),
        ),
    ]
