# Generated by Django 2.1.14 on 2020-02-20 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petshow', '0006_petonshow'),
    ]

    operations = [
        migrations.AddField(
            model_name='petonshow',
            name='is_winner',
            field=models.BooleanField(default=False),
        ),
    ]
